### ISSUE TITLE
Error launching config: unable to expand ${file_path}/${file_base_name}

### ISSUE THREAD

**Issue by SomedudeX** [daveleroy/SublimeDebugger#235] opened 2023-12-28 01:07 UTC
#### Issue

See title

#### Debugger Settings
<img width="1396" alt="Screenshot 2023-12-27 at 5 00 31 PM" src="https://github.com/daveleroy/SublimeDebugger/assets/101906945/011df9c3-16a4-43a3-800b-e9541eafc9f6">

#### Error
<img width="511" alt="Screenshot 2023-12-27 at 5 00 38 PM" src="https://github.com/daveleroy/SublimeDebugger/assets/101906945/87a673bd-650b-45eb-9135-fbc379bebb2b">

Needless to say this worked without any issues with sublime's built in "build system".

**Comment by daveleroy** [comment] 2024-01-08 20:45
This is a duplicate of https://github.com/daveleroy/SublimeDebugger/issues/215

**Closed by daveleroy** 2024-01-08 20:45 UTC
