### ISSUE TITLE
Debugger UI scaling/region issue

### ISSUE THREAD

**Issue by SomedudeX** [daveleroy/SublimeDebugger#253] opened 2024-03-22 01:42 UTC
I have encountered an issue where the variables section of the debugger panel gets "squished" down below the callstack/breakpoints panels. See video and image for more details

https://github.com/daveleroy/SublimeDebugger/assets/101906945/da37baca-5961-45a8-98af-41ec7de93210

<img width="1920" alt="Screenshot 2024-03-21 at 18 23 22" src="https://github.com/daveleroy/SublimeDebugger/assets/101906945/3c35f46e-edf8-4b53-8e67-d8539388078e">

This issue stops if I go into Debugger's settings and change the ui scale to be lower than 4. I am happy to provide more information if necessary.

**Comment by daveleroy** [comment] 2024-03-22 03:12
This is a duplicate of https://github.com/daveleroy/SublimeDebugger/issues/223

**Closed by daveleroy** 2024-03-22 03:12 UTC
